### PR TITLE
Issue 48 Added Angular application

### LINKED ISSUE #48: Add Angular App to ASPN.NET Project

### PR DESCRIPTION
**Pull request by Alfer-Star**
Hier stand Mist

### CODE REVIEW

**Comment by Alfer-Star** [comment]
Ignore Angular instanc on Port used by ng serve:

[See here: ](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=netcore-cli#create-a-new-app)

> The app starts up an instance of the Angular CLI server in the background. A message similar to the following is logged: NG Live Development Server is listening on localhost:<otherport>, open a browser to http://localhost:<otherport>/. Ignore this message—it's not the URL for the combined ASP.NET Core and Angular CLI app.

**Comment by Alfer-Star** [comment]
Instance on :5000 need fix, because of Errors

I will try these [fix on stackoverflow](https://stackoverflow.com/a/50634408):

**Comment by olohr** [comment]
Added an auth system now, it's basically using the graph token like before and the angular app can make a request to the server to get the authentication status of the user, currently it only includes the claims. This would be cached and used for further authorization stuff in the angular app, at least that would be my idea. However, there is another neat option I want to look into, which is a JWT, which can be created by the ASP.NET backend and sent to angular after authentication, so that the additional http request to get the auth state is not necessary anymore and I think angular has better support for JWT?

**Comment by olohr** [comment]
Angular is in a working state now, so I'm merging it now, even tough:
- the transition isn't entirely complete (legal notice and the entire person stuff is still in asp.net)
- authentication is kinda scuffed, permissions is more of a placeholder for out actual plans (see #50 )
- no actual component that does anything has been implemented
- the layout rework isn't reflected

However, these things belong in seperate PRs imo

**Pull request merged**
